### ISSUE TITLE
"make install" does not work

### ISSUE THREAD

**Issue by probonopd** [Leinnan/mybelka#1]
```
$ make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
make: Nothing to be done for `install'.
```

I would expect it to install the application into the system, along with a desktop file and icon. Please change your `.pro` file it similar to https://github.com/probonopd/FeedTheMonkey/blob/master/FeedTheMonkey.pro.

Reference:
https://travis-ci.org/probonopd/mybelka/builds/299913610#L725-L726

**Comment by Leinnan** [comment]
After I will done basic GUI version I will take care of this.

**Comment by Leinnan** [comment]
@probonopd  Try now on branch _feature/ui_

**Comment by probonopd** [comment]
Thank you very much. However, the build now fails with

```
main.cpp:(.text.startup+0x22f): undefined reference to `la::CliManager::CliManager()'
main.cpp:(.text.startup+0x6e1): undefined reference to `la::CliManager::applySettings(QSettings*)'
main.cpp:(.text.startup+0x76f): undefined reference to `la::CliManager::addTransaction()'
main.cpp:(.text.startup+0x836): undefined reference to `la::CliManager::runMenu()'
collect2: error: ld returned 1 exit status
```

Reference:
https://travis-ci.org/probonopd/mybelka/builds/309360637#L723-L727

**Comment by Leinnan** [comment]
Oh, you need to specify CLI or GUI version by adding 'CONFIG+=ui_gfx' or 'CONFIG+=ui_cli' to yours qmake command.
